apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: csapp-pvc
  namespace: csns
  labels:
    app: cs
    name: csapp-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
