apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bgg
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: bgg
  template: 
    metadata: 
      name: bggdb-po
      labels:
        app: bgg
    spec: 
      containers: 
      - name: bgg-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 3306
---

apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
spec:
  ## dont want to expose, therefore use ClusterIP
  type: ClusterIP
  selector: 
    app: bgg
  ports:
  - port: 3306
    targetPort: 3306
