apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minio
data:
  MINIO_ROOT_USER: root
    
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQ=
