---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minio
spec:
  clusterIP: None
  selector:
    name: minio-po
  ports:
  - name: data 
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio
spec:
  type: ClusterIP
  selector:
    name: minio-po
  ports:
  - name: data 
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: minio
spec:
  replicas: 3
  serviceName: minio-hsvc
  selector:
    matchLabels:
      name: minio-po
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      name: minio-po
      labels: 
        name: minio-po
    spec:
      initContainers:
      - name: change-perms
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "chmod 777 /data"
        volumeMounts:
        - name: data-vol
          mountPath: /data

      containers:
      - name: minio-container
        image: bitnami/minio:2023.9.23
        imagePullPolicy: IfNotPresent
        command:
        - minio
        - server
        - --address=:9000
        - --console-address=:9090
        - http://minio-sts-{0...2}.minio-hsvc.minio.svc.cluster.local/data
        envFrom: 
        - configMapRef:
            name: minio-cm
        - secretRef:
            name: minio-secret
        volumeMounts:
        - name: data-vol
          mountPath: /data
        ports:
        - name: data
          containerPort: 9000
        - name: console
          containerPort: 9090
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          periodSeconds: 60


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ing
  namespace: minio
  labels:
    name: minio-ing
spec:
  ingressClassName: nginx
  rules:
  - host: console-188.166.205.188.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9090
  - host: data-188.166.205.188.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9000
